### ISSUE TITLE
[FEAT] Key specs (Master issue) for First logic implementation

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/resslab-astra_82001#6]
- [x]  Re-add license
- [x] possibilité de rendre alpha q1  et c dynamique en fonction du alpha dynamique avec les différentes versions
- [x] Button to download documentation from astra_82001.xlsx
- [x] Display properly width108 in the dataset, with a tableau de correspondance. 
  * Wid12 -> 12m. Wid108 -> 10m80. Width108 -> display "≥9m".

- [x] Add a new input for beta : le default c'est 4.2 et on peut choisir le 4.7
  - on mettra le 4.7 pour les ouvrages cat.3 prioritaire

- [x] Add a new input for dynamic factor (phycal)  le default c'est 1.0 et on peut choisir le 1.15.
   * le Phy Cal est seulement pour les ponts de moins de 20m (voir page 88 et 89)
  - La valeur par défault doit être 1.00 ( car l'ofrou pourrait décidé d'ajouter un facteur != 1.00)
  - Si l'etat de la chaussé ne peut pas être déterminé (ou n'est pas qualifié des très bon)
    𝐿 ≤ 10 𝑚, 𝑐𝑎𝑙 = 1.15
    10 < 𝐿 ≤ 20 𝑚, 𝜑𝑐𝑎𝑙 = 1.15 − 0.015 ∙ (𝐿 − 10)
    𝐿 > 20 𝑚, 𝜑𝑐𝑎𝑙 = 1.00
  - Par défaut c'est 1.00

- [x] Remplacer dans l'UI : "Transversal or Longitudinal" par "Poutre"

- [x] Formule : Afficher toujours 0.30 si inférieur à 0.30.

**Comment by guilbep** [comment]
<img width="1798" alt="first-draft-astra-82001" src="https://github.com/user-attachments/assets/2a4908c6-2b9b-4023-9c99-ef94120a5a0b">
